### ISSUE TITLE
[BUG]: Cypher injection 

### ISSUE THREAD

**Issue by karranb** [CheesecakeLabs/neo4j-node-ogm#26]
### Description of the bug

find clauses are not using parameters therefore they can be used for cypher injection

### Steps To Reproduce

Entity.findBy([{ key: 'any', value: "'a"}]) 

will throw Cypher ERROR: Invalid input 'a'

because the result query is similar to:
```
\"MATCH (entity:ENTITY)  WHERE  entity.any = ''a'\"
```

**Comment by natamvo** [comment]
done on #33
